### ISSUE TITLE
Issue running on android

### ISSUE THREAD

**Issue by prasanthdevu** [telerik/xamarin-forms-sdk#3]
Issue running the code on android.
Following error on startup itself:-
![Capture](https://user-images.githubusercontent.com/30460877/78502220-92754e00-777d-11ea-97c2-e0db857119ea.JPG)

**Comment by vanka78bg** [comment]
This error message seems very similar to an issue already reported to Microsoft: [InvalidOperationException while debugging Xamarin Forms app](https://developercommunityapi.westus.cloudapp.azure.com/content/problem/873127/invalidoperationexception-while-debugging-xamarin.html). The good news is, it has already been fixed. Please, try to update to the latest version of Visual Studio. If the problem persists even after updating to the latest version of Visual Studio, please, let us know.

**Comment by prasanthdevu** [comment]
I was using VS 16.5.1 upgrading it to VS 16.5.2 solved the issue. Thanks.
